#!/usr/bin/env bash
#
# Build StretchCat.app — a universal (arm64 + x86_64) menu-bar app bundle.
#
# By default this produces a locally-runnable, ad-hoc-signed app so you can
# test immediately. For notarized distribution, pass a Developer ID identity:
#
#   ./build.sh                                   # ad-hoc sign (local testing)
#   ./build.sh "Developer ID Application: Name (TEAMID)"   # release sign
#
# Notarization + DMG + release are handled by scripts/make_dmg.sh and
# scripts/release.sh after this produces the .app.
set -euo pipefail

cd "$(dirname "$0")"

APP_NAME="StretchCat"
BUNDLE_ID="com.khoivo.stretchcat"
VERSION="1.2.0"
BUILD="3"
SIGN_IDENTITY="${1:--}"   # default "-" = ad-hoc

APP_DIR="build/${APP_NAME}.app"
MACOS_DIR="${APP_DIR}/Contents/MacOS"
RES_DIR="${APP_DIR}/Contents/Resources"

echo "==> Building universal release binary"
swift build -c release --arch arm64 --arch x86_64

BIN_PATH="$(swift build -c release --arch arm64 --arch x86_64 --show-bin-path)/${APP_NAME}"

echo "==> Assembling ${APP_DIR}"
rm -rf "${APP_DIR}"
mkdir -p "${MACOS_DIR}" "${RES_DIR}"
cp "${BIN_PATH}" "${MACOS_DIR}/${APP_NAME}"
cp "Resources/cat.png" "${RES_DIR}/cat.png"
cp "Resources/cat_stretch.mp4" "${RES_DIR}/cat_stretch.mp4"
cp "Resources/MenuBarCat.png" "${RES_DIR}/MenuBarCat.png"
cp "Resources/MenuBarCat@2x.png" "${RES_DIR}/MenuBarCat@2x.png"

# App icon (generated by scripts/make_icon.sh if present)
if [ -f "Resources/AppIcon.icns" ]; then
    cp "Resources/AppIcon.icns" "${RES_DIR}/AppIcon.icns"
    ICON_KEY="<key>CFBundleIconFile</key><string>AppIcon</string>"
else
    ICON_KEY=""
fi

echo "==> Writing Info.plist"
cat > "${APP_DIR}/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key><string>${APP_NAME}</string>
    <key>CFBundleDisplayName</key><string>Stretch Cat</string>
    <key>CFBundleIdentifier</key><string>${BUNDLE_ID}</string>
    <key>CFBundleVersion</key><string>${BUILD}</string>
    <key>CFBundleShortVersionString</key><string>${VERSION}</string>
    <key>CFBundleExecutable</key><string>${APP_NAME}</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>LSMinimumSystemVersion</key><string>13.0</string>
    <key>LSUIElement</key><true/>
    <key>NSHumanReadableCopyright</key><string>Stretch Cat</string>
    ${ICON_KEY}
</dict>
</plist>
PLIST

echo "==> Stripping extended attributes"
# iCloud Drive (this repo lives under ~/Documents) re-stamps com.apple.FinderInfo
# onto the freshly written bundle, which codesign rejects as "detritus". A single
# strip can lose the race, so strip-and-verify with a few retries until the
# rejectable attrs are actually gone (com.apple.provenance is fine — codesign
# accepts it).
for _ in 1 2 3 4 5; do
    xattr -cr "${APP_DIR}"
    if ! xattr -rl "${APP_DIR}" | grep -qE 'FinderInfo|ResourceFork'; then
        break
    fi
    sleep 1
done

echo "==> Code signing (identity: ${SIGN_IDENTITY})"
if [ "${SIGN_IDENTITY}" = "-" ]; then
    codesign --force --deep --sign - "${APP_DIR}"
else
    codesign --force --options runtime --timestamp \
        --entitlements StretchCat.entitlements \
        --sign "${SIGN_IDENTITY}" "${APP_DIR}"
fi

echo "==> Done: ${APP_DIR}"
codesign -dvv "${APP_DIR}" 2>&1 | grep -E "Identifier|Authority|Signature" || true
echo ""
echo "Run it with:  open ${APP_DIR}"
