#!/usr/bin/env bash
#
# Full release pipeline for the direct-download channel:
#   build (signed) -> notarize -> DMG (notarized) -> GitHub release -> cask bump
#
# Requirements (set as env vars):
#   DEV_ID_APP      e.g. "Developer ID Application: Khoi Vo (ZNG57U88R5)"
#   NOTARY_PROFILE  notarytool keychain profile name (see README "Publishing")
#   VERSION         e.g. 1.0.0   (defaults to the value in build.sh)
#   GH_REPO         e.g. VoMinhKhoii/StretchCat
set -euo pipefail
cd "$(dirname "$0")/.."

VERSION="${VERSION:-1.0.0}"
GH_REPO="${GH_REPO:-VoMinhKhoii/StretchCat}"
: "${DEV_ID_APP:?set DEV_ID_APP to your Developer ID Application identity}"
: "${NOTARY_PROFILE:?set NOTARY_PROFILE to your notarytool keychain profile}"

# Release must run from a clean main so the auto-generated cask PR carries only
# the cask bump (and the release tag lands on main).
CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [ "$CURRENT_BRANCH" != "main" ]; then
    echo "❌ release must run from main (current: $CURRENT_BRANCH)"; exit 1
fi
if [ -n "$(git status --porcelain)" ]; then
    echo "❌ working tree must be clean before releasing"; exit 1
fi

echo "==> 1/5 Building + signing app"
./build.sh "$DEV_ID_APP"

echo "==> 2/5 Notarizing app"
rm -f build/StretchCat.zip
ditto -c -k --keepParent build/StretchCat.app build/StretchCat.zip
xcrun notarytool submit build/StretchCat.zip --keychain-profile "$NOTARY_PROFILE" --wait
xcrun stapler staple build/StretchCat.app
# re-zip the stapled app for the zip asset
rm -f build/StretchCat.zip
ditto -c -k --keepParent build/StretchCat.app build/StretchCat.zip

echo "==> 3/5 Building + notarizing DMG"
DEV_ID_APP="$DEV_ID_APP" NOTARY_PROFILE="$NOTARY_PROFILE" bash scripts/make_dmg.sh

DMG_SHA=$(shasum -a 256 build/StretchCat.dmg | awk '{print $1}')
echo "    DMG sha256: $DMG_SHA"

echo "==> 4/5 Creating GitHub release v$VERSION"
gh release create "v$VERSION" \
    build/StretchCat.dmg build/StretchCat.zip \
    --repo "$GH_REPO" \
    --title "Stretch Cat v$VERSION" \
    --notes "Menu-bar app that reminds you to stand up and stretch every 2 hours, starring an animated calico cat. Notarized for Gatekeeper.

**Install:** download \`StretchCat.dmg\`, open it, drag Stretch Cat to Applications.
**Or:** \`brew install --cask vominhkhoii/stretch-cat/stretch-cat\`"

echo "==> 5/5 Updating Homebrew cask"
DOWNLOAD_URL="https://github.com/${GH_REPO}/releases/download/v${VERSION}/StretchCat.dmg"
sed -e "s|__VERSION__|${VERSION}|g" \
    -e "s|__SHA256__|${DMG_SHA}|g" \
    -e "s|__URL__|${DOWNLOAD_URL}|g" \
    Casks/stretch-cat.rb.tmpl > Casks/stretch-cat.rb
echo "    wrote Casks/stretch-cat.rb"

# main is a protected branch (requires a PR), so the cask bump can't be pushed
# straight to it — open a PR from a dedicated branch instead.
if [ -z "$(git status --porcelain -- Casks/stretch-cat.rb)" ]; then
    echo "    cask already current — no PR needed"
else
    ORIG_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
    CASK_BRANCH="cask-bump-v${VERSION}"
    echo "    opening a PR from ${CASK_BRANCH} (main is protected)"
    git checkout -B "$CASK_BRANCH"
    git add Casks/stretch-cat.rb
    git commit -q -m "Update Homebrew cask to v${VERSION}"
    git push -u origin "$CASK_BRANCH" --force-with-lease
    if ! gh pr create --repo "$GH_REPO" --base main --head "$CASK_BRANCH" \
        --title "Update Homebrew cask to v${VERSION}" \
        --body "Automated cask bump for the v${VERSION} release.

- version → \`${VERSION}\`
- sha256 → \`${DMG_SHA}\`
- url → ${DOWNLOAD_URL}

Generated by \`scripts/release.sh\`. Review and merge to finish publishing."; then
        echo "❌ failed to open cask PR for ${CASK_BRANCH} (a PR may already exist, or auth/network failed)" >&2
        git checkout "$ORIG_BRANCH" >/dev/null 2>&1 || true
        exit 1
    fi
    git checkout "$ORIG_BRANCH" >/dev/null 2>&1 || true
    echo "    ↳ review & merge the cask PR so 'brew install --cask' picks up v${VERSION}"
fi

echo ""
echo "✅ Released v$VERSION."
